--tools option (o)

diff --git a/bin/stup b/bin/stup
--- a/bin/stup
+++ b/bin/stup
@@ -15,6 +15,7 @@
       echo      '  stup --python         # install Python 3.11'
       echo      '  stup --profile        # install ~/bin/profile.sh'
       echo      '  stup --tree           # install tree'
+      echo      '  stup --tools          # install tools of tool-stup repo'
       echo      '  stup --vamos          # install vamos'
       echo      '  stup --wd             # install ec, idb and wd'
       echo      '  stup --zsdk           # install Zephyr software development kit'
@@ -56,7 +57,7 @@
 #===============================================================================
 
    if [ "$*" == "--version" ] || [ "$*" == "--v" ]; then
-      echo "1.0.0n"
+      echo "1.0.0o"
       return 0 2>/dev/null || exit 0  # safe return/exit
    fi
 
@@ -737,6 +738,37 @@
       sudo chmod +x $BIN/tv
 
       exit 0
+   fi
+
+#===============================================================================
+# stup ----tools   # install tools
+#===============================================================================
+
+   if [ "$*" == "--vamos" ]; then
+      stup ---g '=== install tools ...'
+
+      if [ "`which pimp`" == "" ]; then
+         stup ---r "error: pimp not installed => fix with: stup --pimp"
+         exit 1
+      fi
+
+      if [ ! -d ~/tmp ]; then mkdir ~/tmp; fi
+      if [ ! -d ~/bin ]; then mkdir ~/bin; fi
+
+      rm -rf ~/tmp/tool-stup || exit 1
+      cd tmp || exit 1
+
+      URL=https://github.com/bluccino/tool-stup
+      stup ---y "git clone $URL"
+      git clone $URL || exit 1
+
+      cd tool-stup
+      pimp -d ~/bin
+
+         # cleanup
+
+      cd ..
+      rm -rf tool-stup
    fi
 
 #===============================================================================
